apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
data:
  example-mapping.json: |
    {{ .Values.wiremock.mapping | indent 4 }}