apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}
spec:
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
